DEVICE_PATH := device/kyocera/js201
BOARD_VENDOR := kyocera
BOARD_DEVICE := js201
TARGET_DEVICE := js201
TARGET_SOC := msm8916
TARGET_BOARD_PLATFORM := Qualcomm

# Build options
ALLOW_MISSING_DEPENDENCIES := true
BOARD_SUPPRESS_SECURE_ERASE := true
TARGET_OTA_ASSERT_DEVICE := SZJ-JS201,js201
TARGET_BOOTLOADER_BOARD_NAME := msm8916
TARGET_BOARD_PLATFORM_GPU := qcom-adreno306
TARGET_PLATFORM_DEVICE_BASE := /devices/soc.0/
RECOVERY_VARIANT := twrp
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := true
TARGET_NO_FACTORYIMAGE :=true
TARGET_NO_BOOTLOADER := true
TARGET_NO_RADIOIMAGE := true


# Disabled features
BOARD_PROVIDES_LIBRIL := false
BOARD_PROVIDES_RILD := false
BOARD_HAS_NFC := false
BOARD_HAS_RADIO := false
BOARD_HAS_HDMI := false

# Architecture
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_ABI2 :=
TARGET_CPU_VARIANT := generic
TARGET_CPU_SMP := true

TARGET_2ND_ARCH := arm
TARGET_2ND_ARCH_VARIANT := armv7-a-neon
TARGET_2ND_CPU_ABI := armeabi-v7a
TARGET_2ND_CPU_ABI2 := armeabi
TARGET_2ND_CPU_VARIANT := generic
TARGET_CPU_ABI_LIST_64_BIT := $(TARGET_CPU_ABI)
TARGET_CPU_ABI_LIST_32_BIT := $(TARGET_2ND_CPU_ABI),$(TARGET_2ND_CPU_ABI2)
TARGET_CPU_ABI_LIST := $(TARGET_CPU_ABI_LIST_64_BIT),$(TARGET_CPU_ABI_LIST_32_BIT)
TARGET_CPU_MEMCPY_OPT_DISABLE := true
ARCH_ARM_HAVE_TLS_REGISTER := true
TARGET_SCREEN_DENSITY := 160

# OTA

AB_OTA_UPDATER := false

# Display

DEVICE_RESOLUTION := 1280x800
LANDSCAPE_RESOLUTION := 1280x800
PORTRAIT_RESOLUTION := 800x1280
NUM_FRAMEBUFFER_SURFACE_BUFFERS := 2
TARGET_RECOVERY_PIXEL_FORMAT := "BGRA_8888"
TARGET_DISABLE_TRIPLE_BUFFERING := true
# Properties

TARGET_SYSTEM_PROP := $(DEVICE_PATH)/system.prop

# File systems

BOARD_HAS_LARGE_FILESYSTEM := true

BOARD_FLASH_BLOCK_SIZE := 131072
BOARD_BOOTIMAGE_PARTITION_SIZE := 33554432
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 33554432
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 1996488704
BOARD_SYSTEMIMAGE_PARTITION_TYPE := ext4
BOARD_USERDATAIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_USES_MMCUTILS := true
BOARD_HAS_NO_MISC_PARTITION := true

# Kernel

BOARD_KERNEL_BASE := 0x80000000
BOARD_KERNEL_CMDLINE := console=ttyHSL0,115200,n8 \
    no_console_suspend=1 \
    androidboot.console=ttyHSL0 \
    androidboot.hardware=qcom \
    msm_rtb.filter=0x237 \
    ehci-hcd.park=3 \
    androidboot.bootdevice=7824900.sdhci \
    lpm_levels.sleep_disabled=1 \
    earlyprintk
BOARD_KERNEL_PAGESIZE := 2048
BOARD_RAMDISK_OFFSET := 0x01000000
BOARD_KERNEL_TAGS_OFFSET := 0x00000100
BOARD_KERNEL_OFFSET := 0x00008000
BOARD_SECOND_OFFSET := 0x00f00000
TARGET_FORCE_PREBUILT_DT := $(DEVICE_PATH)/prebuilt/dt

BOARD_MKBOOTIMG_ARGS := \
     --base $(BOARD_KERNEL_BASE) \
     --pagesize $(BOARD_KERNEL_PAGESIZE) \
     --kernel_offset $(BOARD_KERNEL_OFFSET) \
     --ramdisk_offset $(BOARD_RAMDISK_OFFSET) \
     --tags_offset $(BOARD_KERNEL_TAGS_OFFSET) \
     --second_offset $(BOARD_SECOND_OFFSET) \
     --cmdline "$(BOARD_KERNEL_CMDLINE)" \
     --dt $(TARGET_FORCE_PREBUILT_DT)

# Kernel - prebuilt
TARGET_FORCE_PREBUILT_KERNEL := true
ifeq ($(TARGET_FORCE_PREBUILT_KERNEL),true)
TARGET_PREBUILT_KERNEL := $(DEVICE_PATH)/prebuilt/kernel
PRODUCT_COPY_FILES += \
    $(DEVICE_PATH)/prebuilt/kernel:kernel
endif


# Recovery

TARGET_USERIMAGES_USE_EXT4 := true
RECOVERY_SDCARD_ON_DATA := true
BOARD_RECOVERY_SWIPE := true
BOARD_SUPPRESS_EMMC_WIPE := true
TARGET_USE_CUSTOM_LUN_FILE_PATH := "/sys/class/android_usb/f_mass_storage/lun%d/file"
TARGET_RECOVERY_FSTAB := $(DEVICE_PATH)/recovery/root/etc/recovery.fstab
TARGET_RECOVERY_DEVICE_DIRS += $(DEVICE_PATH)
BOARD_HAS_NO_REAL_SDCARD := true
TW_NO_EXFAT := true
RECOVERY_FSTAB_VERSION := 2

SELINUX_IGNORE_NEVERALLOWS := true
BOARD_HAS_NO_SELECT_BUTTON := true
TW_NO_BATT_PERCENT := true
TW_MAX_BRIGHTNESS := 255
TW_DEFAULT_BRIGHTNESS := 128 
TW_USE_TOOLBOX := false
TW_THEME := landscape_mdpi
TW_SCREEN_WIDTH := 1280
TW_SCREEN_HEIGHT := 800
TW_EXTRA_LANGUAGES := false
TW_USE_INPUT_EVENTS := true
TW_INCLUDE_INJECTTWRP := false
# TW_INPUT_BLACKLIST := hbtp_vm
TW_INPUT_BLACKLIST := FreescaleAccelerometer
TW_NO_SCREEN_TIMEOUT := true
TW_EXCLUDE_BASH := true
TW_EXCLUDE_NANO := true
TW_EXCLUDE_LZMA := true
TW_EXCLUDE_SED := true
TW_EXCLUDE_MTP := true
TW_NO_BZIP2 := true
TW_EXCLUDE_DEFAULT_USB_INIT := true
TW_DEVICE_VERSION := $(shell date -u +" %F")
TW_EXCLUDE_TAR := true
TW_EXCLUDE_ENCRYPTED_BACKUPS := true
TW_EXCLUDE_TWRPAPP := true
TW_EXCLUDE_SUPERSU := true
TW_EXCLUDE_PYTHON := true
TW_DEFAULT_LANGUAGE := en
TW_EXCLUDE_GZIP := true
TW_EXCLUDE_XZ := true
TW_NO_CPU_TEMP := true
TW_NO_HAPTICS := true
TW_ALWAYS_RMRF := true
TW_EXCLUDE_TZDATA := true
TW_NO_EXFAT_FUSE := true
TW_NO_USB_STORAGE := true
TARGET_USES_LOGD := false
TWRP_INCLUDE_LOGCAT := false
TW_NO_REBOOT_BOOTLOADER := true
TW_INTERNAL_STORAGE_PATH := "/data/media/0"
TW_INTERNAL_STORAGE_MOUNT_POINT := "data"
TW_EXTERNAL_STORAGE_PATH := "/external_sd"
TW_EXTERNAL_STORAGE_MOUNT_POINT := "external_sd"
