PRODUCT_SHIPPING_API_LEVEL := 22
PRODUCT_FIRST_API_LEVEL := 22
PRODUCT_CHARACTERISTICS := tablet
TARGET_IS_TABLET := true
TARGET_NO_TELEPHONY := true
TARGET_HAS_NO_RADIO := true
LOCAL_PATH := device/kyocera/js201
